/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Viewer;

/**
 *
 * @author Tomer Efraim
 */
public class QuestionFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public QuestionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        nextButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        answerButton0 = new javax.swing.JRadioButton();
        answerButton1 = new javax.swing.JRadioButton();
        answerButton2 = new javax.swing.JRadioButton();
        answerButton3 = new javax.swing.JRadioButton();
        answerButton4 = new javax.swing.JRadioButton();
        answerButton5 = new javax.swing.JRadioButton();
        answerButton6 = new javax.swing.JRadioButton();
        answerButton7 = new javax.swing.JRadioButton();
        answerButton8 = new javax.swing.JRadioButton();
        answerButton9 = new javax.swing.JRadioButton();
        answerButton10 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionDescriptionArea = new javax.swing.JTextArea();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nextButton.setText("Next");
        nextButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        

        finishButton.setText("Finish");
        finishButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        

        answerButton0.setText("0");
        

        answerButton1.setText("1");
        

        answerButton2.setText("2");
        

        answerButton3.setText("3");
        

        answerButton4.setText("4");
        

        answerButton5.setText("5");
        

        answerButton6.setText("6");
        

        answerButton7.setText("7");
        

        answerButton8.setText("8");
        

        answerButton9.setText("9");
        

        answerButton10.setText("10");
        
		

        jScrollPane1.setMinimumSize(new java.awt.Dimension(2, 2));
        jScrollPane1.setName(""); // NOI18N

        questionDescriptionArea.setColumns(20);
        questionDescriptionArea.setRows(2);
        jScrollPane1.setViewportView(questionDescriptionArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(answerButton10)
                                    .addComponent(answerButton9)
                                    .addComponent(answerButton8)
                                    .addComponent(answerButton7)
                                    .addComponent(answerButton6)
                                    .addComponent(answerButton5)
                                    .addComponent(answerButton4)
                                    .addComponent(answerButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(answerButton2)
                                    .addComponent(answerButton1)
                                    .addComponent(answerButton0))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(127, 127, 127))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(answerButton0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
    public javax.swing.JRadioButton answerButton0;
    public javax.swing.JRadioButton answerButton1;
    public javax.swing.JRadioButton answerButton10;
    public javax.swing.JRadioButton answerButton2;
    public javax.swing.JRadioButton answerButton3;
    public javax.swing.JRadioButton answerButton4;
    public javax.swing.JRadioButton answerButton5;
    public javax.swing.JRadioButton answerButton6;
    public javax.swing.JRadioButton answerButton7;
    public javax.swing.JRadioButton answerButton8;
    public javax.swing.JRadioButton answerButton9;
    public javax.swing.JButton finishButton;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea jTextArea2;
    public javax.swing.JButton nextButton;
    public javax.swing.JTextArea questionDescriptionArea;
}
