/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Viewer;

/**
 *
 * @author Tomer Efraim
 */
public class ResultFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyResultFrame
     */
    public ResultFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        partyList = new javax.swing.JComboBox<>();
        requirementList = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        weightTextArea = new javax.swing.JTextArea();
        showButton = new javax.swing.JButton();
        pickPartyLabel = new javax.swing.JLabel();
        pickRequirementLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		String[] petStrings = { "The Zionist Camp", "Likud", "The Jewish Home", "The Arabs Party", "Yehadut Hatora", "Shas", "Kulanu", "Yesh Atid", "Meretz", "Israel Beitenu"};
        partyList = new javax.swing.JComboBox(petStrings);

		String req1 = "Mendatory military service";
		String req2 = "Appartment for young couples";
		String req3 = "Building settlements over the green line";
		String req4 = "Relief in converting to judaism";
		String req5 = "Accepting civil marriage";
		String req6 = "Public transport in shabbat";
		String req7 = "Permission to keep foreign currency";
		String[] reqStrings = {req1, req2, req3, req4, req5, req6, req7};
        requirementList = new javax.swing.JComboBox(reqStrings);

        weightTextArea.setColumns(20);
        weightTextArea.setRows(1);
        jScrollPane1.setViewportView(weightTextArea);

        showButton.setText("Show Average Weight");

        pickPartyLabel.setText("Pick Party:");

        pickRequirementLabel.setText("Pick Requirement:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(partyList, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(requirementList, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(showButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(pickPartyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pickRequirementLabel)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pickPartyLabel)
                    .addComponent(pickRequirementLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partyList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requirementList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(showButton)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> partyList;
    public javax.swing.JLabel pickPartyLabel;
    public javax.swing.JLabel pickRequirementLabel;
    public javax.swing.JComboBox<String> requirementList;
    public javax.swing.JButton showButton;
    public javax.swing.JTextArea weightTextArea;

}
